/*
Deployment script for MainDB

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar BuildConfiguration "Release"
:setvar DatabaseName "MainDB"
:setvar DefaultFilePrefix "MainDB"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Dropping Default Constraint [dbo].[DF_Birthday_CreatedOn]...';


GO
ALTER TABLE [dbo].[Birthday] DROP CONSTRAINT [DF_Birthday_CreatedOn];


GO
PRINT N'Dropping Default Constraint [dbo].[DF_Channel_CreatedOn]...';


GO
ALTER TABLE [dbo].[Channel] DROP CONSTRAINT [DF_Channel_CreatedOn];


GO
PRINT N'Dropping Default Constraint [dbo].[DF_ChannelType_CreatedOn]...';


GO
ALTER TABLE [dbo].[ChannelType] DROP CONSTRAINT [DF_ChannelType_CreatedOn];


GO
PRINT N'Dropping Default Constraint [dbo].[DF_CustomCommand_CreatedOn]...';


GO
ALTER TABLE [dbo].[CustomCommand] DROP CONSTRAINT [DF_CustomCommand_CreatedOn];


GO
PRINT N'Dropping Default Constraint [dbo].[DF_Embed_CreatedOn]...';


GO
ALTER TABLE [dbo].[Embed] DROP CONSTRAINT [DF_Embed_CreatedOn];


GO
PRINT N'Dropping Default Constraint [dbo].[DF_Embed_ModifiedOn]...';


GO
ALTER TABLE [dbo].[Embed] DROP CONSTRAINT [DF_Embed_ModifiedOn];


GO
PRINT N'Dropping Default Constraint [dbo].[DF_EmbedGroup_CreatedOn]...';


GO
ALTER TABLE [dbo].[EmbedGroup] DROP CONSTRAINT [DF_EmbedGroup_CreatedOn];


GO
PRINT N'Dropping Default Constraint [dbo].[DF_Greeting_CreatedOn]...';


GO
ALTER TABLE [dbo].[Greeting] DROP CONSTRAINT [DF_Greeting_CreatedOn];


GO
PRINT N'Dropping Default Constraint [dbo].[DF_Idol_CreatedOn]...';


GO
ALTER TABLE [dbo].[Idol] DROP CONSTRAINT [DF_Idol_CreatedOn];


GO
PRINT N'Dropping Default Constraint [dbo].[DF_Idol_ModifiedOn]...';


GO
ALTER TABLE [dbo].[Idol] DROP CONSTRAINT [DF_Idol_ModifiedOn];


GO
PRINT N'Dropping Default Constraint [dbo].[DF_IdolAlias_CreatedOn]...';


GO
ALTER TABLE [dbo].[IdolAlias] DROP CONSTRAINT [DF_IdolAlias_CreatedOn];


GO
PRINT N'Dropping Default Constraint [dbo].[DF_IdolGroup_CreatedOn]...';


GO
ALTER TABLE [dbo].[IdolGroup] DROP CONSTRAINT [DF_IdolGroup_CreatedOn];


GO
PRINT N'Dropping Default Constraint [dbo].[DF_IdolGroup_ModifiedOn]...';


GO
ALTER TABLE [dbo].[IdolGroup] DROP CONSTRAINT [DF_IdolGroup_ModifiedOn];


GO
PRINT N'Dropping Default Constraint [dbo].[DF_IdolImage_CreatedOn]...';


GO
ALTER TABLE [dbo].[IdolImage] DROP CONSTRAINT [DF_IdolImage_CreatedOn];


GO
PRINT N'Dropping Default Constraint [dbo].[DF_Reminder_CreatedOn]...';


GO
ALTER TABLE [dbo].[Reminder] DROP CONSTRAINT [DF_Reminder_CreatedOn];


GO
PRINT N'Dropping Default Constraint [dbo].[DF_Role_CreatedOn]...';


GO
ALTER TABLE [dbo].[Role] DROP CONSTRAINT [DF_Role_CreatedOn];


GO
PRINT N'Dropping Default Constraint [dbo].[DF_Server_CreatedOn]...';


GO
ALTER TABLE [dbo].[Server] DROP CONSTRAINT [DF_Server_CreatedOn];


GO
PRINT N'Dropping Default Constraint [dbo].[DF_Server_ModifiedOn]...';


GO
ALTER TABLE [dbo].[Server] DROP CONSTRAINT [DF_Server_ModifiedOn];


GO
PRINT N'Dropping Default Constraint [dbo].[DF_TwitchChannel_CreatedOn]...';


GO
ALTER TABLE [dbo].[TwitchChannel] DROP CONSTRAINT [DF_TwitchChannel_CreatedOn];


GO
PRINT N'Dropping Default Constraint [dbo].[DF_User_CreatedOn]...';


GO
ALTER TABLE [dbo].[User] DROP CONSTRAINT [DF_User_CreatedOn];


GO
PRINT N'Dropping Default Constraint [dbo].[DF_User_ModifiedOn]...';


GO
ALTER TABLE [dbo].[User] DROP CONSTRAINT [DF_User_ModifiedOn];


GO
PRINT N'Dropping Default Constraint [dbo].[DF_UseIdolStatistic_CreatedOn]...';


GO
ALTER TABLE [dbo].[UserIdolStatistic] DROP CONSTRAINT [DF_UseIdolStatistic_CreatedOn];


GO
PRINT N'Dropping Default Constraint [dbo].[DF_UseIdolStatistic_ModifiedOn]...';


GO
ALTER TABLE [dbo].[UserIdolStatistic] DROP CONSTRAINT [DF_UseIdolStatistic_ModifiedOn];


GO
PRINT N'Dropping Default Constraint [dbo].[DF_WeeklyPoll_CreatedOn]...';


GO
ALTER TABLE [dbo].[WeeklyPoll] DROP CONSTRAINT [DF_WeeklyPoll_CreatedOn];


GO
PRINT N'Dropping Default Constraint [dbo].[DF_WeeklyPoll_ModifiedOn]...';


GO
ALTER TABLE [dbo].[WeeklyPoll] DROP CONSTRAINT [DF_WeeklyPoll_ModifiedOn];


GO
PRINT N'Dropping Default Constraint [dbo].[DF_WeeklyPollOption_CreatedOn]...';


GO
ALTER TABLE [dbo].[WeeklyPollOption] DROP CONSTRAINT [DF_WeeklyPollOption_CreatedOn];


GO
PRINT N'Dropping Default Constraint [dbo].[DF_WeeklyPollOption_ModifiedOn]...';


GO
ALTER TABLE [dbo].[WeeklyPollOption] DROP CONSTRAINT [DF_WeeklyPollOption_ModifiedOn];


GO
PRINT N'Dropping Default Constraint [dbo].[DF_WeeklyPollOptionPreset_CreatedOn]...';


GO
ALTER TABLE [dbo].[WeeklyPollOptionPreset] DROP CONSTRAINT [DF_WeeklyPollOptionPreset_CreatedOn];


GO
PRINT N'Dropping Default Constraint [dbo].[DF_WeeklyPollOptionPreset_ModifiedOn]...';


GO
ALTER TABLE [dbo].[WeeklyPollOptionPreset] DROP CONSTRAINT [DF_WeeklyPollOptionPreset_ModifiedOn];


GO
PRINT N'Dropping Check Constraint [dbo].[CK_WeeklyPoll_RepeatOnDayOfWeek]...';


GO
ALTER TABLE [dbo].[WeeklyPoll] DROP CONSTRAINT [CK_WeeklyPoll_RepeatOnDayOfWeek];


GO
PRINT N'Creating Table [dbo].[ServerTrackedStreamSource]...';


GO
CREATE TABLE [dbo].[ServerTrackedStreamSource] (
    [ServerTrackedStreamSourceId] INT           IDENTITY (1, 1) NOT NULL,
    [SourceSite]                  VARCHAR (100) NOT NULL,
    [SourceLink]                  VARCHAR (300) NOT NULL,
    [SourceUsername]              VARCHAR (150) NOT NULL,
    [ServerId]                    INT           NOT NULL,
    [CreatedOn]                   DATETIME      NOT NULL,
    [TwitchId]                    VARCHAR (12)  NOT NULL,
    CONSTRAINT [PK_ServerTrackedStreamSourceId] PRIMARY KEY CLUSTERED ([ServerTrackedStreamSourceId] ASC)
);


GO
PRINT N'Creating Default Constraint [dbo].[DF_Birthday_CreatedOn]...';


GO
ALTER TABLE [dbo].[Birthday]
    ADD CONSTRAINT [DF_Birthday_CreatedOn] DEFAULT GETUTCDATE() FOR [CreatedOn];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Channel_CreatedOn]...';


GO
ALTER TABLE [dbo].[Channel]
    ADD CONSTRAINT [DF_Channel_CreatedOn] DEFAULT GETUTCDATE() FOR [CreatedOn];


GO
PRINT N'Creating Default Constraint [dbo].[DF_ChannelType_CreatedOn]...';


GO
ALTER TABLE [dbo].[ChannelType]
    ADD CONSTRAINT [DF_ChannelType_CreatedOn] DEFAULT GETUTCDATE() FOR [CreatedOn];


GO
PRINT N'Creating Default Constraint [dbo].[DF_CustomCommand_CreatedOn]...';


GO
ALTER TABLE [dbo].[CustomCommand]
    ADD CONSTRAINT [DF_CustomCommand_CreatedOn] DEFAULT GETUTCDATE() FOR [CreatedOn];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Embed_CreatedOn]...';


GO
ALTER TABLE [dbo].[Embed]
    ADD CONSTRAINT [DF_Embed_CreatedOn] DEFAULT GETUTCDATE() FOR [CreatedOn];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Embed_ModifiedOn]...';


GO
ALTER TABLE [dbo].[Embed]
    ADD CONSTRAINT [DF_Embed_ModifiedOn] DEFAULT GETUTCDATE() FOR [ModifiedOn];


GO
PRINT N'Creating Default Constraint [dbo].[DF_EmbedGroup_CreatedOn]...';


GO
ALTER TABLE [dbo].[EmbedGroup]
    ADD CONSTRAINT [DF_EmbedGroup_CreatedOn] DEFAULT GETUTCDATE() FOR [CreatedOn];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Greeting_CreatedOn]...';


GO
ALTER TABLE [dbo].[Greeting]
    ADD CONSTRAINT [DF_Greeting_CreatedOn] DEFAULT GETUTCDATE() FOR [CreatedOn];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Idol_CreatedOn]...';


GO
ALTER TABLE [dbo].[Idol]
    ADD CONSTRAINT [DF_Idol_CreatedOn] DEFAULT GETUTCDATE() FOR [CreatedOn];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Idol_ModifiedOn]...';


GO
ALTER TABLE [dbo].[Idol]
    ADD CONSTRAINT [DF_Idol_ModifiedOn] DEFAULT GETUTCDATE() FOR [ModifiedOn];


GO
PRINT N'Creating Default Constraint [dbo].[DF_IdolAlias_CreatedOn]...';


GO
ALTER TABLE [dbo].[IdolAlias]
    ADD CONSTRAINT [DF_IdolAlias_CreatedOn] DEFAULT GETUTCDATE() FOR [CreatedOn];


GO
PRINT N'Creating Default Constraint [dbo].[DF_IdolGroup_CreatedOn]...';


GO
ALTER TABLE [dbo].[IdolGroup]
    ADD CONSTRAINT [DF_IdolGroup_CreatedOn] DEFAULT GETUTCDATE() FOR [CreatedOn];


GO
PRINT N'Creating Default Constraint [dbo].[DF_IdolGroup_ModifiedOn]...';


GO
ALTER TABLE [dbo].[IdolGroup]
    ADD CONSTRAINT [DF_IdolGroup_ModifiedOn] DEFAULT GETUTCDATE() FOR [ModifiedOn];


GO
PRINT N'Creating Default Constraint [dbo].[DF_IdolImage_CreatedOn]...';


GO
ALTER TABLE [dbo].[IdolImage]
    ADD CONSTRAINT [DF_IdolImage_CreatedOn] DEFAULT GETUTCDATE() FOR [CreatedOn];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Reminder_CreatedOn]...';


GO
ALTER TABLE [dbo].[Reminder]
    ADD CONSTRAINT [DF_Reminder_CreatedOn] DEFAULT GETUTCDATE() FOR [CreatedOn];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Role_CreatedOn]...';


GO
ALTER TABLE [dbo].[Role]
    ADD CONSTRAINT [DF_Role_CreatedOn] DEFAULT GETUTCDATE() FOR [CreatedOn];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Server_CreatedOn]...';


GO
ALTER TABLE [dbo].[Server]
    ADD CONSTRAINT [DF_Server_CreatedOn] DEFAULT GETUTCDATE() FOR [CreatedOn];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Server_ModifiedOn]...';


GO
ALTER TABLE [dbo].[Server]
    ADD CONSTRAINT [DF_Server_ModifiedOn] DEFAULT GETUTCDATE() FOR [ModifiedOn];


GO
PRINT N'Creating Default Constraint [dbo].[DF_TwitchChannel_CreatedOn]...';


GO
ALTER TABLE [dbo].[TwitchChannel]
    ADD CONSTRAINT [DF_TwitchChannel_CreatedOn] DEFAULT GETUTCDATE() FOR [CreatedOn];


GO
PRINT N'Creating Default Constraint [dbo].[DF_User_CreatedOn]...';


GO
ALTER TABLE [dbo].[User]
    ADD CONSTRAINT [DF_User_CreatedOn] DEFAULT GETUTCDATE() FOR [CreatedOn];


GO
PRINT N'Creating Default Constraint [dbo].[DF_User_ModifiedOn]...';


GO
ALTER TABLE [dbo].[User]
    ADD CONSTRAINT [DF_User_ModifiedOn] DEFAULT GETUTCDATE() FOR [ModifiedOn];


GO
PRINT N'Creating Default Constraint [dbo].[DF_UseIdolStatistic_CreatedOn]...';


GO
ALTER TABLE [dbo].[UserIdolStatistic]
    ADD CONSTRAINT [DF_UseIdolStatistic_CreatedOn] DEFAULT GETUTCDATE() FOR [CreatedOn];


GO
PRINT N'Creating Default Constraint [dbo].[DF_UseIdolStatistic_ModifiedOn]...';


GO
ALTER TABLE [dbo].[UserIdolStatistic]
    ADD CONSTRAINT [DF_UseIdolStatistic_ModifiedOn] DEFAULT GETUTCDATE() FOR [ModifiedOn];


GO
PRINT N'Creating Default Constraint [dbo].[DF_WeeklyPoll_CreatedOn]...';


GO
ALTER TABLE [dbo].[WeeklyPoll]
    ADD CONSTRAINT [DF_WeeklyPoll_CreatedOn] DEFAULT GETUTCDATE() FOR [CreatedOn];


GO
PRINT N'Creating Default Constraint [dbo].[DF_WeeklyPoll_ModifiedOn]...';


GO
ALTER TABLE [dbo].[WeeklyPoll]
    ADD CONSTRAINT [DF_WeeklyPoll_ModifiedOn] DEFAULT GETUTCDATE() FOR [ModifiedOn];


GO
PRINT N'Creating Default Constraint [dbo].[DF_WeeklyPollOption_CreatedOn]...';


GO
ALTER TABLE [dbo].[WeeklyPollOption]
    ADD CONSTRAINT [DF_WeeklyPollOption_CreatedOn] DEFAULT GETUTCDATE() FOR [CreatedOn];


GO
PRINT N'Creating Default Constraint [dbo].[DF_WeeklyPollOption_ModifiedOn]...';


GO
ALTER TABLE [dbo].[WeeklyPollOption]
    ADD CONSTRAINT [DF_WeeklyPollOption_ModifiedOn] DEFAULT GETUTCDATE() FOR [ModifiedOn];


GO
PRINT N'Creating Default Constraint [dbo].[DF_WeeklyPollOptionPreset_CreatedOn]...';


GO
ALTER TABLE [dbo].[WeeklyPollOptionPreset]
    ADD CONSTRAINT [DF_WeeklyPollOptionPreset_CreatedOn] DEFAULT GETUTCDATE() FOR [CreatedOn];


GO
PRINT N'Creating Default Constraint [dbo].[DF_WeeklyPollOptionPreset_ModifiedOn]...';


GO
ALTER TABLE [dbo].[WeeklyPollOptionPreset]
    ADD CONSTRAINT [DF_WeeklyPollOptionPreset_ModifiedOn] DEFAULT GETUTCDATE() FOR [ModifiedOn];


GO
PRINT N'Creating Default Constraint [dbo].[DF_ServerTrackedStreamSource_CreatedOn]...';


GO
ALTER TABLE [dbo].[ServerTrackedStreamSource]
    ADD CONSTRAINT [DF_ServerTrackedStreamSource_CreatedOn] DEFAULT GETUTCDATE() FOR [CreatedOn];


GO
PRINT N'Creating Foreign Key [dbo].[FK_ServerTrackedStreamSource_Server]...';


GO
ALTER TABLE [dbo].[ServerTrackedStreamSource] WITH NOCHECK
    ADD CONSTRAINT [FK_ServerTrackedStreamSource_Server] FOREIGN KEY ([ServerId]) REFERENCES [dbo].[Server] ([ServerId]);


GO
PRINT N'Creating Check Constraint [dbo].[CK_WeeklyPoll_RepeatOnDayOfWeek]...';


GO
ALTER TABLE [dbo].[WeeklyPoll] WITH NOCHECK
    ADD CONSTRAINT [CK_WeeklyPoll_RepeatOnDayOfWeek] CHECK ([RepeatOnDayOfWeek] IN ('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'));


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[ServerTrackedStreamSource] WITH CHECK CHECK CONSTRAINT [FK_ServerTrackedStreamSource_Server];

ALTER TABLE [dbo].[WeeklyPoll] WITH CHECK CHECK CONSTRAINT [CK_WeeklyPoll_RepeatOnDayOfWeek];


GO
PRINT N'Update complete.';


GO
