/*
Deployment script for MainDB

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar BuildConfiguration "Release"
:setvar DatabaseName "MainDB"
:setvar DefaultFilePrefix "MainDB"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
/*
Table [dbo].[Keyword] is being dropped.
*/

PRINT N'Rename refactoring operation with key 207577b6-d947-4aef-bcd2-155b6a3c3470 is skipped, element [dbo].[WeeklyPoll].[Id] (SqlSimpleColumn) will not be renamed to WeeklyPollId';


GO
PRINT N'Rename refactoring operation with key bc0bae62-5b14-46de-a13c-ac0d3aad6088 is skipped, element [dbo].[WeeklyPoll].[PollTitle] (SqlSimpleColumn) will not be renamed to Title';


GO
PRINT N'Rename refactoring operation with key 689ad98d-2570-40b2-bf46-d3ea8fa32728, cf065e26-8fc7-4176-8a98-71a6dca9811a, 2fb38c42-d074-4fc4-9ca8-914c5787985e is skipped, element [dbo].[WeeklyPoll].[PollCloseInInterval] (SqlSimpleColumn) will not be renamed to CloseInTimeSpanTicks';


GO
PRINT N'Rename refactoring operation with key f4d7b05c-fc37-4ef9-ba73-5cfb9186c190, 19d09f66-174e-494c-9789-7030617bc7fb is skipped, element [dbo].[WeeklyPoll].[RepeatOn] (SqlSimpleColumn) will not be renamed to RepeatOnDayOfWeek';


GO
PRINT N'Rename refactoring operation with key e925e534-52de-4679-8f5e-7120c04a3c9e is skipped, element [dbo].[WeeklyPollOption].[Id] (SqlSimpleColumn) will not be renamed to WeeklyPollOptionId';


GO
PRINT N'Rename refactoring operation with key 6c554721-fd22-4d3d-9375-22325503d367, eb18290c-7419-4b00-b5ce-a9ac96cc7b78 is skipped, element [dbo].[WeeklyPollOption].[PresetId] (SqlSimpleColumn) will not be renamed to WeeklyPollOptionPresetId';


GO
PRINT N'Rename refactoring operation with key d5cd4a43-7f60-4209-a180-439d46ff6289 is skipped, element [dbo].[WeeklyPollOptionPreset].[Id] (SqlSimpleColumn) will not be renamed to WeeklyPollOptionPresetId';


GO
PRINT N'Dropping Default Constraint [dbo].[DF_Keyword_CreatedOn]...';


GO
ALTER TABLE [dbo].[Keyword] DROP CONSTRAINT [DF_Keyword_CreatedOn];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_Keyword_Server]...';


GO
ALTER TABLE [dbo].[Keyword] DROP CONSTRAINT [FK_Keyword_Server];


GO
PRINT N'Dropping Table [dbo].[Keyword]...';


GO
DROP TABLE [dbo].[Keyword];


GO
PRINT N'Dropping View [dbo].[ServerChannelView]...';


GO
DROP VIEW [dbo].[ServerChannelView];


GO
PRINT N'Dropping User [laptop_adam]...';


GO
DROP USER [laptop_adam];


GO
PRINT N'Creating Table [dbo].[WeeklyPoll]...';


GO
CREATE TABLE [dbo].[WeeklyPoll] (
    [WeeklyPollId]         INT            IDENTITY (1, 1) NOT NULL,
    [ServerId]             INT            NOT NULL,
    [ChannelId]            INT            NOT NULL,
    [RoleId]               INT            NULL,
    [Name]                 NVARCHAR (50)  NOT NULL,
    [Title]                NVARCHAR (300) NOT NULL,
    [CloseInTimeSpanTicks] BIGINT         NOT NULL,
    [RepeatOnDayOfWeek]    VARCHAR (10)   NOT NULL,
    [IsMultipleAnswer]     BIT            NOT NULL,
    [OptionPresetId]       INT            NULL,
    [IsActive]             BIT            NOT NULL,
    [CreatedOn]            DATETIME       NOT NULL,
    [ModifiedOn]           DATETIME       NOT NULL,
    CONSTRAINT [PK_WeeklyPollId] PRIMARY KEY CLUSTERED ([WeeklyPollId] ASC)
);


GO
PRINT N'Creating Table [dbo].[WeeklyPollOption]...';


GO
CREATE TABLE [dbo].[WeeklyPollOption] (
    [WeeklyPollOptionId]       INT           IDENTITY (1, 1) NOT NULL,
    [WeeklyPollId]             INT           NULL,
    [WeeklyPollOptionPresetId] INT           NULL,
    [OrderNumber]              TINYINT       NOT NULL,
    [Title]                    NVARCHAR (55) NOT NULL,
    [CreatedOn]                DATETIME      NOT NULL,
    [ModifiedOn]               DATETIME      NOT NULL,
    CONSTRAINT [PK_WeeklyPollOptionId] PRIMARY KEY CLUSTERED ([WeeklyPollOptionId] ASC)
);


GO
PRINT N'Creating Table [dbo].[WeeklyPollOptionPreset]...';


GO
CREATE TABLE [dbo].[WeeklyPollOptionPreset] (
    [WeeklyPollOptionPresetId] INT            IDENTITY (1, 1) NOT NULL,
    [Name]                     NVARCHAR (100) NOT NULL,
    [Description]              NVARCHAR (100) NOT NULL,
    [IsSpecialPreset]          BIT            NOT NULL,
    [IsActive]                 BIT            NOT NULL,
    [CreatedOn]                DATETIME       NOT NULL,
    [ModifiedOn]               DATETIME       NOT NULL,
    CONSTRAINT [PK_WeeklyPollOptionPresetId] PRIMARY KEY CLUSTERED ([WeeklyPollOptionPresetId] ASC)
);


GO
PRINT N'Creating Default Constraint [dbo].[DF_WeeklyPoll_IsActive]...';


GO
ALTER TABLE [dbo].[WeeklyPoll]
    ADD CONSTRAINT [DF_WeeklyPoll_IsActive] DEFAULT 1 FOR [IsActive];


GO
PRINT N'Creating Default Constraint [dbo].[DF_WeeklyPoll_CreatedOn]...';


GO
ALTER TABLE [dbo].[WeeklyPoll]
    ADD CONSTRAINT [DF_WeeklyPoll_CreatedOn] DEFAULT GETDATE() FOR [CreatedOn];


GO
PRINT N'Creating Default Constraint [dbo].[DF_WeeklyPoll_ModifiedOn]...';


GO
ALTER TABLE [dbo].[WeeklyPoll]
    ADD CONSTRAINT [DF_WeeklyPoll_ModifiedOn] DEFAULT GETDATE() FOR [ModifiedOn];


GO
PRINT N'Creating Default Constraint [dbo].[DF_WeeklyPollOption_CreatedOn]...';


GO
ALTER TABLE [dbo].[WeeklyPollOption]
    ADD CONSTRAINT [DF_WeeklyPollOption_CreatedOn] DEFAULT GETDATE() FOR [CreatedOn];


GO
PRINT N'Creating Default Constraint [dbo].[DF_WeeklyPollOption_ModifiedOn]...';


GO
ALTER TABLE [dbo].[WeeklyPollOption]
    ADD CONSTRAINT [DF_WeeklyPollOption_ModifiedOn] DEFAULT GETDATE() FOR [ModifiedOn];


GO
PRINT N'Creating Default Constraint [dbo].[DF_WeeklyPollOptionPreset_IsSpecialPreset]...';


GO
ALTER TABLE [dbo].[WeeklyPollOptionPreset]
    ADD CONSTRAINT [DF_WeeklyPollOptionPreset_IsSpecialPreset] DEFAULT 0 FOR [IsSpecialPreset];


GO
PRINT N'Creating Default Constraint [dbo].[DF_WeeklyPollOptionPreset_IsActive]...';


GO
ALTER TABLE [dbo].[WeeklyPollOptionPreset]
    ADD CONSTRAINT [DF_WeeklyPollOptionPreset_IsActive] DEFAULT 1 FOR [IsActive];


GO
PRINT N'Creating Default Constraint [dbo].[DF_WeeklyPollOptionPreset_CreatedOn]...';


GO
ALTER TABLE [dbo].[WeeklyPollOptionPreset]
    ADD CONSTRAINT [DF_WeeklyPollOptionPreset_CreatedOn] DEFAULT GETDATE() FOR [CreatedOn];


GO
PRINT N'Creating Default Constraint [dbo].[DF_WeeklyPollOptionPreset_ModifiedOn]...';


GO
ALTER TABLE [dbo].[WeeklyPollOptionPreset]
    ADD CONSTRAINT [DF_WeeklyPollOptionPreset_ModifiedOn] DEFAULT GETDATE() FOR [ModifiedOn];


GO
PRINT N'Creating Foreign Key [dbo].[FK_WeeklyPoll_ServerId]...';


GO
ALTER TABLE [dbo].[WeeklyPoll] WITH NOCHECK
    ADD CONSTRAINT [FK_WeeklyPoll_ServerId] FOREIGN KEY ([ServerId]) REFERENCES [dbo].[Server] ([ServerId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_WeeklyPoll_ChannelId]...';


GO
ALTER TABLE [dbo].[WeeklyPoll] WITH NOCHECK
    ADD CONSTRAINT [FK_WeeklyPoll_ChannelId] FOREIGN KEY ([ChannelId]) REFERENCES [dbo].[Channel] ([ChannelId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_WeeklyPoll_RoleId]...';


GO
ALTER TABLE [dbo].[WeeklyPoll] WITH NOCHECK
    ADD CONSTRAINT [FK_WeeklyPoll_RoleId] FOREIGN KEY ([RoleId]) REFERENCES [dbo].[Role] ([RoleId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_WeeklyPoll_WeeklyPollOptionPresetId]...';


GO
ALTER TABLE [dbo].[WeeklyPoll] WITH NOCHECK
    ADD CONSTRAINT [FK_WeeklyPoll_WeeklyPollOptionPresetId] FOREIGN KEY ([OptionPresetId]) REFERENCES [dbo].[WeeklyPollOptionPreset] ([WeeklyPollOptionPresetId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_WeeklyPollOption_WeeklyPollId]...';


GO
ALTER TABLE [dbo].[WeeklyPollOption] WITH NOCHECK
    ADD CONSTRAINT [FK_WeeklyPollOption_WeeklyPollId] FOREIGN KEY ([WeeklyPollId]) REFERENCES [dbo].[WeeklyPoll] ([WeeklyPollId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_WeeklyPollOption_WeeklyPollOptionPresetId]...';


GO
ALTER TABLE [dbo].[WeeklyPollOption] WITH NOCHECK
    ADD CONSTRAINT [FK_WeeklyPollOption_WeeklyPollOptionPresetId] FOREIGN KEY ([WeeklyPollOptionPresetId]) REFERENCES [dbo].[WeeklyPollOptionPreset] ([WeeklyPollOptionPresetId]);


GO
PRINT N'Creating Check Constraint [dbo].[CK_WeeklyPoll_RepeatOnDayOfWeek]...';


GO
ALTER TABLE [dbo].[WeeklyPoll] WITH NOCHECK
    ADD CONSTRAINT [CK_WeeklyPoll_RepeatOnDayOfWeek] CHECK ([RepeatOnDayOfWeek] IN ('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'));


GO
PRINT N'Creating Check Constraint [dbo].[CK_WeeklyPollOption_OrderNumber]...';


GO
ALTER TABLE [dbo].[WeeklyPollOption] WITH NOCHECK
    ADD CONSTRAINT [CK_WeeklyPollOption_OrderNumber] CHECK ([OrderNumber] >= 0 AND [OrderNumber] < 10);


GO
-- Refactoring step to update target server with deployed transaction logs
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '207577b6-d947-4aef-bcd2-155b6a3c3470')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('207577b6-d947-4aef-bcd2-155b6a3c3470')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'bc0bae62-5b14-46de-a13c-ac0d3aad6088')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('bc0bae62-5b14-46de-a13c-ac0d3aad6088')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '689ad98d-2570-40b2-bf46-d3ea8fa32728')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('689ad98d-2570-40b2-bf46-d3ea8fa32728')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'cf065e26-8fc7-4176-8a98-71a6dca9811a')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('cf065e26-8fc7-4176-8a98-71a6dca9811a')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'f4d7b05c-fc37-4ef9-ba73-5cfb9186c190')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('f4d7b05c-fc37-4ef9-ba73-5cfb9186c190')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '19d09f66-174e-494c-9789-7030617bc7fb')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('19d09f66-174e-494c-9789-7030617bc7fb')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '7a7dd630-35ce-4d04-9aa0-34acaaef5733')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('7a7dd630-35ce-4d04-9aa0-34acaaef5733')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '2fb38c42-d074-4fc4-9ca8-914c5787985e')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('2fb38c42-d074-4fc4-9ca8-914c5787985e')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '8c883e6a-6a4c-418d-a85f-d93256e767cf')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('8c883e6a-6a4c-418d-a85f-d93256e767cf')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'e925e534-52de-4679-8f5e-7120c04a3c9e')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('e925e534-52de-4679-8f5e-7120c04a3c9e')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '6c554721-fd22-4d3d-9375-22325503d367')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('6c554721-fd22-4d3d-9375-22325503d367')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'd5cd4a43-7f60-4209-a180-439d46ff6289')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('d5cd4a43-7f60-4209-a180-439d46ff6289')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'eb18290c-7419-4b00-b5ce-a9ac96cc7b78')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('eb18290c-7419-4b00-b5ce-a9ac96cc7b78')

GO

GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[WeeklyPoll] WITH CHECK CHECK CONSTRAINT [FK_WeeklyPoll_ServerId];

ALTER TABLE [dbo].[WeeklyPoll] WITH CHECK CHECK CONSTRAINT [FK_WeeklyPoll_ChannelId];

ALTER TABLE [dbo].[WeeklyPoll] WITH CHECK CHECK CONSTRAINT [FK_WeeklyPoll_RoleId];

ALTER TABLE [dbo].[WeeklyPoll] WITH CHECK CHECK CONSTRAINT [FK_WeeklyPoll_WeeklyPollOptionPresetId];

ALTER TABLE [dbo].[WeeklyPollOption] WITH CHECK CHECK CONSTRAINT [FK_WeeklyPollOption_WeeklyPollId];

ALTER TABLE [dbo].[WeeklyPollOption] WITH CHECK CHECK CONSTRAINT [FK_WeeklyPollOption_WeeklyPollOptionPresetId];

ALTER TABLE [dbo].[WeeklyPoll] WITH CHECK CHECK CONSTRAINT [CK_WeeklyPoll_RepeatOnDayOfWeek];

ALTER TABLE [dbo].[WeeklyPollOption] WITH CHECK CHECK CONSTRAINT [CK_WeeklyPollOption_OrderNumber];


GO
PRINT N'Update complete.';


GO
