/*
Deployment script for MainDB

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar BuildConfiguration "Release"
:setvar DatabaseName "MainDB"
:setvar DefaultFilePrefix "MainDB"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Altering Table [dbo].[Birthday]...';


GO
ALTER TABLE [dbo].[Birthday]
    ADD [CreatedOn] DATETIME DEFAULT GETDATE() NOT NULL;


GO
PRINT N'Altering Table [dbo].[Channel]...';


GO
ALTER TABLE [dbo].[Channel]
    ADD [CreatedOn] DATETIME DEFAULT GETDATE() NOT NULL;


GO
PRINT N'Altering Table [dbo].[ChannelType]...';


GO
ALTER TABLE [dbo].[ChannelType]
    ADD [CreatedOn] DATETIME DEFAULT GETDATE() NOT NULL;


GO
PRINT N'Altering Table [dbo].[CustomCommand]...';


GO
ALTER TABLE [dbo].[CustomCommand]
    ADD [CreatedOn] DATETIME DEFAULT GETDATE() NOT NULL;


GO
PRINT N'Altering Table [dbo].[Greeting]...';


GO
ALTER TABLE [dbo].[Greeting]
    ADD [CreatedOn] DATETIME DEFAULT GETDATE() NOT NULL;


GO
PRINT N'Altering Table [dbo].[Idol]...';


GO
ALTER TABLE [dbo].[Idol]
    ADD [ProfileUrl]      NVARCHAR (200) NULL,
        [StageName]       NVARCHAR (100) NULL,
        [FullName]        NVARCHAR (100) NULL,
        [KoreanFullName]  NVARCHAR (100) NULL,
        [KoreanStageName] NVARCHAR (100) NULL,
        [DateOfBirth]     DATE           NULL,
        [Gender]          VARCHAR (10)   NULL,
        [CreatedOn]       DATETIME       DEFAULT GETDATE() NOT NULL,
        [ModifiedOn]      DATETIME       DEFAULT GETDATE() NOT NULL;


GO
PRINT N'Altering Table [dbo].[IdolAlias]...';


GO
ALTER TABLE [dbo].[IdolAlias]
    ADD [CreatedOn] DATETIME DEFAULT GETDATE() NOT NULL;


GO
PRINT N'Altering Table [dbo].[IdolGroup]...';


GO
ALTER TABLE [dbo].[IdolGroup]
    ADD [DebutDate]      DATE           NULL,
        [FullName]       NVARCHAR (100) NULL,
        [FullKoreanName] NVARCHAR (100) NULL,
        [CreatedOn]      DATETIME       DEFAULT GETDATE() NOT NULL,
        [ModifiedOn]     DATETIME       DEFAULT GETDATE() NOT NULL;


GO
PRINT N'Altering Table [dbo].[IdolImage]...';


GO
ALTER TABLE [dbo].[IdolImage] ALTER COLUMN [ImageURL] NVARCHAR (200) NOT NULL;


GO
ALTER TABLE [dbo].[IdolImage]
    ADD [CreatedOn]  DATETIME DEFAULT GETDATE() NOT NULL;


GO
PRINT N'Altering Table [dbo].[Keyword]...';


GO
ALTER TABLE [dbo].[Keyword]
    ADD [CreatedOn] DATETIME DEFAULT GETDATE() NOT NULL;


GO
PRINT N'Altering Table [dbo].[Reminder]...';


GO
ALTER TABLE [dbo].[Reminder]
    ADD [CreatedOn] DATETIME DEFAULT GETDATE() NOT NULL;


GO
PRINT N'Altering Table [dbo].[Role]...';


GO
ALTER TABLE [dbo].[Role]
    ADD [CreatedOn] DATETIME DEFAULT GETDATE() NOT NULL;


GO
PRINT N'Altering Table [dbo].[Server]...';


GO
ALTER TABLE [dbo].[Server]
    ADD [CreatedOn] DATETIME DEFAULT GETDATE() NOT NULL;


GO
PRINT N'Altering Table [dbo].[TwitchChannel]...';


GO
ALTER TABLE [dbo].[TwitchChannel]
    ADD [CreatedOn] DATETIME DEFAULT GETDATE() NOT NULL;


GO
PRINT N'Altering Table [dbo].[User]...';


GO
ALTER TABLE [dbo].[User]
    ADD [CreatedOn] DATETIME DEFAULT GETDATE() NOT NULL;


GO
PRINT N'Creating Table [dbo].[UserIdolStatistic]...';


GO
CREATE TABLE [dbo].[UserIdolStatistic] (
    [UserId]  INT NOT NULL,
    [IdolId]  INT NOT NULL,
    [Placed1] INT NOT NULL,
    [Placed2] INT NOT NULL,
    [Placed3] INT NOT NULL,
    [Placed4] INT NOT NULL,
    [Placed5] INT NOT NULL,
    CONSTRAINT [PK_UserId_IdolId_UserIdolStatistic] PRIMARY KEY CLUSTERED ([UserId] ASC, [IdolId] ASC)
);


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[UserIdolStatistic]...';


GO
ALTER TABLE [dbo].[UserIdolStatistic]
    ADD DEFAULT 0 FOR [Placed1];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[UserIdolStatistic]...';


GO
ALTER TABLE [dbo].[UserIdolStatistic]
    ADD DEFAULT 0 FOR [Placed2];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[UserIdolStatistic]...';


GO
ALTER TABLE [dbo].[UserIdolStatistic]
    ADD DEFAULT 0 FOR [Placed3];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[UserIdolStatistic]...';


GO
ALTER TABLE [dbo].[UserIdolStatistic]
    ADD DEFAULT 0 FOR [Placed4];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[UserIdolStatistic]...';


GO
ALTER TABLE [dbo].[UserIdolStatistic]
    ADD DEFAULT 0 FOR [Placed5];


GO
PRINT N'Creating Foreign Key [dbo].[FK_UserIdolStatistic_User]...';


GO
ALTER TABLE [dbo].[UserIdolStatistic] WITH NOCHECK
    ADD CONSTRAINT [FK_UserIdolStatistic_User] FOREIGN KEY ([UserId]) REFERENCES [dbo].[User] ([UserId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_UserIdolStatistic_Idol]...';


GO
ALTER TABLE [dbo].[UserIdolStatistic] WITH NOCHECK
    ADD CONSTRAINT [FK_UserIdolStatistic_Idol] FOREIGN KEY ([IdolId]) REFERENCES [dbo].[Idol] ([IdolId]) ON DELETE CASCADE;


GO
PRINT N'Refreshing View [dbo].[ServerChannelView]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[ServerChannelView]';


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[UserIdolStatistic] WITH CHECK CHECK CONSTRAINT [FK_UserIdolStatistic_User];

ALTER TABLE [dbo].[UserIdolStatistic] WITH CHECK CHECK CONSTRAINT [FK_UserIdolStatistic_Idol];


GO
PRINT N'Update complete.';


GO
