/*
Deployment script for MainDB

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar BuildConfiguration "Release"
:setvar DatabaseName "MainDB"
:setvar DefaultFilePrefix "MainDB"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Rename refactoring operation with key b2883bb5-7dd8-40d6-81ea-90b847f1d5a6 is skipped, element [dbo].[ServerMutedUsers].[Id] (SqlSimpleColumn) will not be renamed to ServerId';


GO
PRINT N'Dropping Foreign Key [dbo].[FK_ServerSettingChannel_ChannelType]...';


GO
ALTER TABLE [dbo].[ServerSettingChannel] DROP CONSTRAINT [FK_ServerSettingChannel_ChannelType];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_Server_Role]...';


GO
ALTER TABLE [dbo].[Server] DROP CONSTRAINT [FK_Server_Role];


GO
PRINT N'Altering Table [dbo].[Server]...';


GO
ALTER TABLE [dbo].[Server]
    ADD [MuteRoleId] INT NULL;


GO
PRINT N'Creating Table [dbo].[ServerMutedUsers]...';


GO
CREATE TABLE [dbo].[ServerMutedUsers] (
    [ServerId]   INT      NOT NULL,
    [UserId]     INT      NOT NULL,
    [MutedUntil] DATETIME NOT NULL,
    [RemovedRoleDiscordIds] NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_Muted_ServerId_UserId] PRIMARY KEY CLUSTERED ([UserId] ASC, [ServerId] ASC)
);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ServerSettingChannel_ChannelType]...';


GO
ALTER TABLE [dbo].[ServerSettingChannel] WITH NOCHECK
    ADD CONSTRAINT [FK_ServerSettingChannel_ChannelType] FOREIGN KEY ([ChannelTypeId]) REFERENCES [dbo].[ChannelType] ([ChannelTypeId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ServerMutedUsers_Server]...';


GO
ALTER TABLE [dbo].[ServerMutedUsers] WITH NOCHECK
    ADD CONSTRAINT [FK_ServerMutedUsers_Server] FOREIGN KEY ([ServerId]) REFERENCES [dbo].[Server] ([ServerId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ServerMutedUsers_User]...';


GO
ALTER TABLE [dbo].[ServerMutedUsers] WITH NOCHECK
    ADD CONSTRAINT [FK_ServerMutedUsers_User] FOREIGN KEY ([UserId]) REFERENCES [dbo].[User] ([UserId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Server_MuteRole]...';


GO
ALTER TABLE [dbo].[Server] WITH NOCHECK
    ADD CONSTRAINT [FK_Server_MuteRole] FOREIGN KEY ([MuteRoleId]) REFERENCES [dbo].[Role] ([RoleId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Server_NotificationRole]...';


GO
ALTER TABLE [dbo].[Server] WITH NOCHECK
    ADD CONSTRAINT [FK_Server_NotificationRole] FOREIGN KEY ([NotificationRoleId]) REFERENCES [dbo].[Role] ([RoleId]);


GO
PRINT N'Refreshing View [dbo].[ServerChannelView]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[ServerChannelView]';


GO
-- Refactoring step to update target server with deployed transaction logs
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'b2883bb5-7dd8-40d6-81ea-90b847f1d5a6')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('b2883bb5-7dd8-40d6-81ea-90b847f1d5a6')

GO

GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[ServerSettingChannel] WITH CHECK CHECK CONSTRAINT [FK_ServerSettingChannel_ChannelType];

ALTER TABLE [dbo].[ServerMutedUsers] WITH CHECK CHECK CONSTRAINT [FK_ServerMutedUsers_Server];

ALTER TABLE [dbo].[ServerMutedUsers] WITH CHECK CHECK CONSTRAINT [FK_ServerMutedUsers_User];

ALTER TABLE [dbo].[Server] WITH CHECK CHECK CONSTRAINT [FK_Server_MuteRole];

ALTER TABLE [dbo].[Server] WITH CHECK CHECK CONSTRAINT [FK_Server_NotificationRole];


GO
PRINT N'Update complete.';


GO
